/* 1280x720: Modeline "1280x720" 74.50 1280 1344 1472 1664 720 723 728 748 -hsync +vsync */
#define HSYNC_POL 1
#define VSYNC_POL 1
#define YPULSE (63+5)
#define XPULSE 128
#define YPIX 720
#define XPIX 1280
#define VFREQ 60
#define DPI 96
#define CLOCK 74500
#define VERSION 1
#define REVISION 3
#define XOFFSET 64
#define YOFFSET (63+3)
#define XY_RATIO XY_RATIO_16_9
#define YBLANK 28
#define XBLANK 384
#define TIMING_NAME "1280x720"
#include "edid.S"
