/* 2560x1440: Modeline "2560x1440" 241.50 2560 2608 2640 2720 1440 1443 1448 1481 +hsync -vsync */
#define HSYNC_POL 1
#define VSYNC_POL 1
#define YPULSE (63+5)
#define XPULSE 32
#define YPIX 1440
#define XPIX 2560
#define VFREQ 60
#define DPI 96
#define CLOCK 241500
#define VERSION 1
#define REVISION 3
#define XOFFSET 48
#define YOFFSET (63+3)
#define XY_RATIO XY_RATIO_16_9
#define YBLANK 41
#define XBLANK 160
#define TIMING_NAME "2560x1440"
#include "edid.S"
