/* 2880x1800: Modeline "2880x1800" 337.75 2880 2928 2960 3040 1800 1803 1809 1852 +hsync -vsync */
#define HSYNC_POL 1
#define VSYNC_POL 1
#define YPULSE (63+6)
#define XPULSE 32
#define YPIX 1800
#define XPIX 2880
#define VFREQ 60
#define DPI 96
#define CLOCK 337750
#define VERSION 1
#define REVISION 3
#define XOFFSET 48
#define YOFFSET (63+3)
#define XY_RATIO XY_RATIO_16_10
#define YBLANK 52
#define XBLANK 160
#define TIMING_NAME "2880x1800"
#include "edid.S"
