/* 3840x2160: Modeline "3840x2160" 594.00 3840 4016 4104 4400 2160 2168 2178 2250 +hsync +vsync */
#define HSYNC_POL 1
#define VSYNC_POL 1
#define YPULSE (63+10)
#define XPULSE 88
#define YPIX 2160
#define XPIX 3840
#define VFREQ 60
#define DPI 96
#define CLOCK 594000
#define VERSION 1
#define REVISION 3
#define XOFFSET 176
#define YOFFSET (63+8)
#define XY_RATIO XY_RATIO_16_9
#define YBLANK 90
#define XBLANK 560
#define TIMING_NAME "3840x2160"
#include "edid.S"
